# Generated by Django 2.0.4 on 2018-05-11 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boodleReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('barracks', models.CharField(max_length=10)),
                ('roomNumber', models.IntegerField()),
                ('receiverCompany', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='boodleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=50)),
                ('timeOfArrival', models.IntegerField()),
                ('additionalInstruction', models.CharField(max_length=250)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boodlerunner.boodleReceiver')),
            ],
        ),
        migrations.CreateModel(
            name='boodleRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnerName', models.CharField(max_length=50)),
                ('runnerPhoneNumber', models.IntegerField()),
                ('runnerBarracks', models.CharField(max_length=10)),
                ('runnerCompany', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boodlerequest',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boodlerunner.boodleRunner'),
        ),
    ]
