# Generated by Django 2.0.4 on 2018-05-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boodlerunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boodlereceiver',
            name='phoneNumber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='boodlereceiver',
            name='roomNumber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='boodlerequest',
            name='timeOfArrival',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='boodlerunner',
            name='runnerPhoneNumber',
            field=models.CharField(max_length=25),
        ),
    ]
