# Generated by Django 2.0.3 on 2018-04-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boodlerunner', '0002_auto_20180404_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boodlerequest',
            name='receiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boodlerunner.boodleReceiver'),
        ),
        migrations.AlterField(
            model_name='boodlerequest',
            name='runnerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boodlerunner.boodleRunner'),
        ),
    ]
